### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by HendrikLeier** [teohaik/jcaliper#1]
I am trying to get this thing to run for two days now...
Since I cannot find any Documentation anywhere its really hard to get this to run...

It would be nice to know:
- Which Java Version
- Which version of eclipse (Since I am getting weird nullpointer exceptions)
- Until which Java version can this analyse
- Are there any other dependencies?

**Comment by teohaik** [comment]
Dear Sir,

thank you for your feedback.

Works with:

Eclipse SDK - Version: 4.2.0
Java version 1.6
Analyzes java projects in java <= 1.6

No other dependencies exist

**Comment by HendrikLeier** [comment]
Thank you for the quick awnser!
